<template>
  <ComplianceGuardWrapper><div class="space-y-6"><div><h1 class="text-2xl font-semibold">人工充值</h1><p class="mt-1 text-sm text-muted-foreground">管理收款二维码并审核用户的扫码转账申请。</p></div>
    <div class="grid gap-6 xl:grid-cols-[380px_1fr]"><section class="rounded-xl border bg-card p-5"><h2 class="font-semibold">收款二维码</h2><form class="mt-4 space-y-3" @submit.prevent="saveChannel"><Input v-model="channel.name" placeholder="名称，例如：微信收款" /><Select v-model="channel.type"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="wechat">微信</SelectItem><SelectItem value="alipay">支付宝</SelectItem></SelectContent></Select><Input v-model="channel.qr_code_url" placeholder="二维码图片地址" /><Input type="file" accept="image/png,image/jpeg,image/webp" @change="uploadQRCode" /><img v-if="channel.qr_code_url" :src="channel.qr_code_url" alt="当前收款二维码" class="h-28 w-28 rounded-lg border bg-white object-contain p-1" /><Input v-model="channel.account_name" placeholder="收款人名称" /><Input v-model="channel.min_amount" placeholder="最低金额，留空不限" /><Input v-model="channel.max_amount" placeholder="最高金额，留空不限" /><Textarea v-model="channel.instructions" placeholder="付款说明" /><label class="flex items-center gap-2 text-sm"><input v-model="channel.enabled" type="checkbox" /> 启用此收款方式</label><Button type="submit">{{ channel.id ? '保存收款方式' : '新增收款方式' }}</Button></form><div class="mt-5 space-y-2"><button v-for="item in channels" :key="item.id" type="button" class="flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-muted/50" @click="edit(item)"><span>{{ item.name }} <small class="text-muted-foreground">{{ item.type }}</small></span><span :class="item.enabled ? 'text-emerald-600' : 'text-muted-foreground'">{{ item.enabled ? '启用' : '停用' }}</span></button></div></section>
    <section class="rounded-xl border bg-card"><div class="flex flex-wrap items-center gap-3 border-b p-4"><Input v-model="keyword" class="max-w-xs" placeholder="申请号、流水号或联系方式" @keyup.enter="load" /><Select v-model="status"><SelectTrigger class="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="">全部状态</SelectItem><SelectItem value="pending">待审核</SelectItem><SelectItem value="processing">核验中</SelectItem><SelectItem value="approved">已到账</SelectItem><SelectItem value="rejected">已拒绝</SelectItem></SelectContent></Select><Button variant="outline" @click="load">筛选</Button></div><div class="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>申请</TableHead><TableHead>用户</TableHead><TableHead>金额</TableHead><TableHead>流水号 / 凭证</TableHead><TableHead>状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="item in rows" :key="item.id"><TableCell><div class="font-mono text-xs">{{ item.request_no }}</div><div class="text-xs text-muted-foreground">{{ item.contact_type }}: {{ item.contact_value }}</div></TableCell><TableCell>#{{ item.user_id }}</TableCell><TableCell class="font-mono">{{ item.amount }} {{ item.currency }}</TableCell><TableCell><div class="max-w-40 truncate">{{ item.transaction_no }}</div><a :href="item.proof_url" target="_blank" class="text-xs text-primary underline">查看截图</a></TableCell><TableCell>{{ item.status }}</TableCell><TableCell><div v-if="['pending','processing'].includes(item.status)" class="flex gap-2"><Button size="sm" @click="approve(item)">通过并入账</Button><Button size="sm" variant="outline" @click="reject(item)">拒绝</Button></div><span v-else class="text-xs text-muted-foreground">{{ item.review_note || '-' }}</span></TableCell></TableRow><TableRow v-if="!rows.length"><TableCell colspan="6" class="py-10 text-center text-muted-foreground">暂无人工充值申请</TableCell></TableRow></TableBody></Table></div></section></div></div></ComplianceGuardWrapper>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { adminAPI } from '@/api/admin'; import ComplianceGuardWrapper from '@/components/ComplianceGuardWrapper.vue'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
const rows = ref<any[]>([]); const channels = ref<any[]>([]); const keyword = ref(''); const status = ref('pending'); const channel = reactive<any>({ id: 0, name: '', type: 'wechat', qr_code_url: '', account_name: '', min_amount: '', max_amount: '', instructions: '', enabled: true, sort: 0 })
const load = async () => { const [requestRes, channelRes] = await Promise.all([adminAPI.getManualRecharges({ page: 1, page_size: 50, keyword: keyword.value || undefined, status: status.value || undefined }), adminAPI.getManualRechargeChannels()]); rows.value = requestRes.data.data || []; channels.value = channelRes.data.data || [] }
const edit = (item: any) => Object.assign(channel, item)
const saveChannel = async () => { if (channel.id) await adminAPI.updateManualRechargeChannel(channel.id, channel); else await adminAPI.createManualRechargeChannel(channel); Object.assign(channel, { id: 0, name: '', type: 'wechat', qr_code_url: '', account_name: '', min_amount: '', max_amount: '', instructions: '', enabled: true, sort: 0 }); await load() }
const uploadQRCode = async (event: Event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); const response = await adminAPI.upload(data, 'manual_recharge'); channel.qr_code_url = response.data.data?.url || channel.qr_code_url }
const approve = async (item: any) => { if (!confirm(`确认给申请 ${item.request_no} 入账 ${item.amount} ${item.currency}？`)) return; await adminAPI.approveManualRecharge(item.id, {}); await load() }
const reject = async (item: any) => { const note = prompt('请输入拒绝原因'); if (!note?.trim()) return; await adminAPI.rejectManualRecharge(item.id, { note }); await load() }
onMounted(() => { void load() })
</script>
